[Interface]
# Key for ANIVOX
# Bouncing = 5
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = mGTL/78qVVBFqmZ7Zfx7/xjVkgWjvV7M7KCcbYxvrX0=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1
MTU = 1360

[Peer]
# UA#48
PublicKey = eqjhoqO6K1nLiej026+RkpSTHloVrOHLlMQaB0Tl5GM=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 156.146.50.5:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a02:6ea0:e108:2054::10]:51820
PersistentKeepalive = 25